version: "3"

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # producer:
  #   container_name: producer
  #   build:
  #     context: producer
  #   ports:
  #     - 3000:3000

  # consumer:
  #   container_name: consumer
  #   build:
  #     context: consumer
  #   ports:
  #     - 3001:3001
